version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12    
    commands:
      - echo Installing Serverless...
      - npm install -g serverless
  pre_build:
    commands:
      - echo Installing source NPM dependencies
      - npm install
  build:
    commands:
      - echo Deployment started on `date`
      - echo Deploying with Serverless Framework
      - sls deploy -v -s $ENV_NAME
  post_build:
    commands:
      - 
